### PR TITLE
main/Faikin: Proper HA fan modes for CN_WIRED

### PR DESCRIPTION
**Pull request by Sonic-Amiga**
C_WIRED uses 3 speeds + auto + quiet (which is called "night" in S21). Our user interface works with that correctly, but HA interface won't understand "quiet". Fix that.

### CODE REVIEW

**Comment by Sonic-Amiga** [comment]
Hello! I managed to find auto-discovery docs on HA web site. And while understanding the code i found this problem, which nobody has reported.

Sorry, this code is untested, it's 1:29 AM here...

**Comment by revk** [comment]
If you can test, that would be great, then I'll merge. Looks reasonably sensible.

**Comment by Sonic-Amiga** [comment]
I will test, but later

BTW, just curious, WDYT about porting Faikin back to Daikin original HW ? I have recently bought an old stock BRP for dissection, it's interesting inside. Based on NXP chip, FreeRTOS of course

**Comment by revk** [comment]
Not sure how hard that would be - you are welcome to try :-)

**Comment by Sonic-Amiga** [comment]
Tested on ESP8266 on both S21 and CN_WIRED; looks OK

**Pull request merged**
