### PR TITLE
FTMX Perfera Control Logic: A bit of structure, comments and variable renaming for better underst…

### PR DESCRIPTION
**Pull request by miniluma**
…anding

It's a bit impolite to do such kind of code changes as a first proposal. Sorry for that. Feel free to disagree to this PR.

I tried to understand your code, so I decided to add some comments and descriptions (I hope I got it right) and also was confused about some variables to I did some find-replace.

### CODE REVIEW

**Comment by revk** [comment]
Hmm...

**Comment by miniluma** [comment]
> Hmm...

If it's too much, leave it as it is and I'll do a new branch with the FTXM logic later based on your original code. Just the control part.

**Comment by revk** [comment]
"You have been accused of not adding documentation in your code, what do you have to say?"

"No comment"

Yes, mostly good, thanks.

Not show of changing naming style on variables. I agree they could be more descriptive, but probably I would use underscores.

**Comment by miniluma** [comment]
Tried to merge in all you latest changes.

**Comment by revk** [comment]
It did not compile, you missed some!

**Comment by miniluma** [comment]
> It did not compile, you missed some!

Shit. Here, it compiled. What did I miss?

**Comment by revk** [comment]
if(t), compare of t and b...

**Comment by miniluma** [comment]
> if(t), compare of t and b...

Grmpf. Ok. Sorry.

**Pull request merged**
