### PR TITLE
Tidy up protocols and their properties

### PR DESCRIPTION
**Pull request by Sonic-Amiga**
No more long repeated fragments like "prototype(proto)" and "protoname[prototype(proto)]". Proper available set of fan speeds for all 3 supported protocols.

Backport from ESP8266

### CODE REVIEW

**Comment by revk** [comment]
Not sure. I'll review next week.

**Comment by Sonic-Amiga** [comment]
> LED strip is another config setting not just blink li

I know, but that's how you did it: https://github.com/revk/ESP32-Faikin/blob/main/ESP32/main/Faikin.c#L2320
```
#ifndef	CONFIG_REVK_BLINK_LIB
void
blink_task (void *p)
{
 led strip stuff here
}
#endif
```
So i just copied your conditional. I don't know how it builds on your side without this fix, the #include is clearly missing.

And yes, i did reset sdkconfig to sdkconfig.defaults

If i keep CONFIG_REVK_BLINK_LIB enabled, i hit another problem: duplicated blink[3] definition in settings.c (autogenerated one). Indeed, it gets duplicated, because first you have on line 135:
```
#ifdef  CONFIG_IDF_TARGET_ESP32S3
revk_settings_gpio_t tx={0};
revk_settings_gpio_t rx={0};
revk_settings_gpio_t blink[3]={0};
#else
revk_settings_gpio_t tx={0};
revk_settings_gpio_t rx={0};
revk_settings_gpio_t blink[3]={0};
#endif
```
and then on line 185:
```
#ifdef	CONFIG_REVK_BLINK_LIB
revk_settings_gpio_t blink[3]={0};
#endif
```

**Comment by Sonic-Amiga** [comment]
> I'll review next week.

Of course, take your time; i am just sharing what i see and what i already went through. Thank you so much for making the great project opensource, it solved my task, i am willing to help,

**Comment by revk** [comment]
I need to tidy "blinking" more anyway.

The library can and should do for simple boards with one status LED.

But some boards had more complex stuff

**Comment by Sonic-Amiga** [comment]
I understand. BTW, my 8266 board only has one LED, so my port uses blinking.

**Comment by revk** [comment]
OK a slight mess. Faikin boards have only one LED. So should be handled by Library.

However, I had the blink GPIOs defined in the Faikin app to make sure I had the right GPIOs for old and new boards.

Now, in practice, I should not have to do that, they should be sticky (fixed settings), so should be set in the config for RevK.

So I should lose the blinking from the Faikin code anyway.

**Comment by Sonic-Amiga** [comment]
Really ? I thought they use an RGB 3-color LED, which is technically 3 LEDs (and your defconfig proves that); and i guess you wanted to use led_strip lib for doing some fancy vfx on them.

**Comment by revk** [comment]
The older ones were a triple LED, and the latest S3 ones are a single LED (WS2812).

**Comment by Sonic-Amiga** [comment]
Understood, thank you for the info.

**Pull request merged**
